### ISSUE TITLE
Missing SignColumn and FoldColumn highlights

### ISSUE THREAD

**Issue by rafi** [jaredgorski/fogbell.vim#1]
Many people use the signcolumn for code and prose analysis, so `set signcolumn=yes` is a popular `.vimrc` setting which always shows the signcolumn at all times. Same story for `FoldColumn` and code folding.

Currently both highlights are being treated and their default don't blend well into the general fogbell theme.

**Comment by jaredgorski** [comment]
Thanks for opening this @rafi, I appreciate the input.

I use `signcolumn=yes`, particularly since I use gitgutter and ALE, and I'm not currently discontent with the colors here. I felt it made sense to keep "diff" colors for the signs and a bright red for errors in the name of practicality. However, I'm curious to hear your thoughts on this since I don't really have an eye for design - what sort of highlights here do you envision as an improvement?

Personally, I rarely use code folding so I haven't seen this until now. Since I use it rarely, I haven't developed preferences on the `foldcolumn`. What would help you here?

**Comment by jaredgorski** [comment]
Closed in https://github.com/jaredgorski/fogbell.vim/commit/274cc13184f6a7d0589650c0763c94cef431b319

**Comment by jaredgorski** [comment]
@rafi I didn't see what you meant until recently - thanks again
