### ISSUE TITLE
all syntax highlight is missing

### ISSUE THREAD

**Issue by winkee01** [jaredgorski/fogbell.vim#2]
After apply this colorscheme, all my syntax highlighting refuse to work.

**Comment by jaredgorski** [comment]
Please clarify; you’re using a colorscheme that has nearly zero syntax highlighting. Sounds like user error to me.

**Comment by winkee01** [comment]
Vim has built-in syntax highlighting supported C/C++ and many other languages, so I don't need to manually apply any syntax highlighting, when I change my colorscheme to fogbell, all syntax highlightings are gone.

here is a screencast
<img width="379" alt="highlight_gone" src="https://user-images.githubusercontent.com/49930785/80788549-014a9900-8bbc-11ea-8552-c644df86c874.png">

**Comment by jaredgorski** [comment]
That looks correct; no bug there. See the screenshots on the README; this colorscheme is complete white on black. That’s the purpose. The Only syntax groups that should not be simple white on black are comments.

**Comment by winkee01** [comment]
> That looks correct; no bug there. See the screenshots on the README; this colorscheme is complete white on black. That’s the purpose. The Only syntax groups that should not be simple white on black are comments.

no syntax highlighting? I don't quite get it. so what's the use of it?

**Comment by jaredgorski** [comment]
After a long time using lots of colors (see my other colorscheme, Spacacamp), I began to wonder whether I was training myself to “code by colors” rather than actually gaining an understanding of the syntactical structure and clarity of my code. I looked into it online and found that there’s a significant minority of programmers who prefer nearly or completely monochrome syntax colors, except perhaps for comments (since those aren’t code). Rob Pike famously prefers black text on a cornsilk yellow background, and there are a number of other colorschemes that do what fogbell does (to varying degrees).

I’ve found I actually quite prefer editing without colors, so if it interests you I encourage you to give it a try. Everyone is different though, so your mileage may vary.

And in case you’re wondering why I don’t just turn `syntax` off, here’s a couple reasons:
- to differentiate comments (as mentioned)
- to customize the contrast ratio
- to enable syntax enrichments in markdown files, vimwiki, etc.

I hope this helps! If you feel satisfied that this isn’t a bug, may I close the issue?

**Comment by jaredgorski** [comment]
@winkee01 - I'll close this issue by end of day if I don't hear back

**Comment by winkee01** [comment]
> After a long time using lots of colors (see my other colorscheme, Spacacamp), I began to wonder whether I was training myself to “code by colors” rather than actually gaining an understanding of the syntactical structure and clarity of my code. I looked into it online and found that there’s a significant minority of programmers who prefer nearly or completely monochrome syntax colors, except perhaps for comments (since those aren’t code). Rob Pike famously prefers black text on a cornsilk yellow background, and there are a number of other colorschemes that do what fogbell does (to varying degrees).
> 
> I’ve found I actually quite prefer editing without colors, so if it interests you I encourage you to give it a try. Everyone is different though, so your mileage may vary.
> 
> And in case you’re wondering why I don’t just turn `syntax` off, here’s a couple reasons:
> 
> * to differentiate comments (as mentioned)
> * to customize the contrast ratio
> * to enable syntax enrichments in markdown files, vimwiki, etc.
> 
> I hope this helps! If you feel satisfied that this isn’t a bug, may I close the issue?

Sorry for the late reply. 

Initially I didn't quite get it, even a bit shock about it, but your explanation regarding to this style of colorscheme is very reasonable and I can understand it now.

I have full respect for your coding philosophy, everyone has his experience and philosophy, so the choice of colorscheme will largely diverge, but I am going to give it a try some day, again, thank you for the explanation.

**Comment by jaredgorski** [comment]
Anytime! Thanks for asking
